version: '3.8'

services:
  nestapp:
    image: iguarnizo21/nestapp:latest #build: ./
    ports:
      - '3000:3000'
    env_file:
      - .env.development
    depends_on:
      - postgresdb
    networks:
      - nestnetwork

  postgresdb:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.development
    networks:
      - nestnetwork

volumes:
  pgdata:

networks: # 👈 Definición de la red (obligatorio)
  nestnetwork:
    driver: bridge
